//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrungTamTinHoc.Resources.UserLang", typeof(UserLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Account.
        /// </summary>
        public static string ActiveAccount {
            get {
                return ResourceManager.GetString("ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully activated your account, please.
        /// </summary>
        public static string ActiveAccountPart1 {
            get {
                return ResourceManager.GetString("ActiveAccountPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to continue using the system.
        /// </summary>
        public static string ActiveAccountPart2 {
            get {
                return ResourceManager.GetString("ActiveAccountPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation information is incorrect, please re-enter your registered email to activate your account.
        /// </summary>
        public static string ActiveAccountPart3 {
            get {
                return ResourceManager.GetString("ActiveAccountPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation information has expired, please re-enter the registered email to activate the account.
        /// </summary>
        public static string ActiveAccountPart4 {
            get {
                return ResourceManager.GetString("ActiveAccountPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All courses.
        /// </summary>
        public static string AllCourses {
            get {
                return ResourceManager.GetString("AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COURSES.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address....
        /// </summary>
        public static string EnterYourEmailAddress {
            get {
                return ResourceManager.GetString("EnterYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide line.
        /// </summary>
        public static string GuideLine {
            get {
                return ResourceManager.GetString("GuideLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have any question?.
        /// </summary>
        public static string HaveAnyQuestion {
            get {
                return ResourceManager.GetString("HaveAnyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with terms conditions.
        /// </summary>
        public static string IAgreeWithTermsConditions {
            get {
                return ResourceManager.GetString("IAgreeWithTermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost your password.
        /// </summary>
        public static string LostPassword {
            get {
                return ResourceManager.GetString("LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string MenuApply {
            get {
                return ResourceManager.GetString("MenuApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string MenuCourses {
            get {
                return ResourceManager.GetString("MenuCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our teacher.
        /// </summary>
        public static string OurTeacher {
            get {
                return ResourceManager.GetString("OurTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Success.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered your account, please check your registered email and click on the attached link to activate your account.
        /// </summary>
        public static string RegisterSuccessPart1 {
            get {
                return ResourceManager.GetString("RegisterSuccessPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular opening.
        /// </summary>
        public static string RegularOpening {
            get {
                return ResourceManager.GetString("RegularOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberLogin {
            get {
                return ResourceManager.GetString("RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend mail.
        /// </summary>
        public static string ResendMail {
            get {
                return ResourceManager.GetString("ResendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here....
        /// </summary>
        public static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To out newsleetter.
        /// </summary>
        public static string ToOutNewsleetter {
            get {
                return ResourceManager.GetString("ToOutNewsleetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userfull Link.
        /// </summary>
        public static string UserfullLink {
            get {
                return ResourceManager.GetString("UserfullLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will you get?.
        /// </summary>
        public static string WhatWillYouGet {
            get {
                return ResourceManager.GetString("WhatWillYouGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY US?.
        /// </summary>
        public static string WhyIpro {
            get {
                return ResourceManager.GetString("WhyIpro", resourceCulture);
            }
        }
    }
}
